### ISSUE TITLE
New release on PyPI with `Optional` usage

### ISSUE THREAD

**Issue by volks73** [nornir/dm4#2]
Hello! Would it be possible to get a new release of the `dm4` package on PyPI with #1 included?

I updated a project from Python v3.8 to v3.9, and I am receiving the following error with Python v3.9 when I use `pip install dm4`:

```
Traceback (most recent call last):
  File "/home/cfield/Code/tsdm/.venv/bin/tsdm", line 5, in <module>
    from tsdm.cli import app
  File "/home/cfield/Code/tsdm/tsdm/cli.py", line 8, in <module>
    from tsdm import (
  File "/home/cfield/Code/tsdm/tsdm/extraction.py", line 2, in <module>
    import dm4
  File "/home/cfield/Code/tsdm/.venv/lib/python3.9/site-packages/dm4/__init__.py", line 7, in <module>
    from dm4.headers import DM4DataType, DM4DirHeader, DM4Header, DM4TagHeader, DM4Config, format_config
  File "/home/cfield/Code/tsdm/.venv/lib/python3.9/site-packages/dm4/headers.py", line 20, in <module>
    class DM4DirHeader(NamedTuple):
  File "/home/cfield/Code/tsdm/.venv/lib/python3.9/site-packages/dm4/headers.py", line 22, in DM4DirHeader
    name: str | None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'
```

If I use the `pip install git+https://github.com/nornir/dm4.git`, then I do not get the error.

As an additional test, I upgraded to Python v3.10 from v3.9 and the error did not occur. I believe the `|` type annotation feature was introduced in Python v3.10. Python v3.9 is [supported until 2025](https://devguide.python.org/versions/).

Thank you again for putting the package on PyPI.

**Comment by jamesra** [comment]
I bumped the version to 1.0.2 and pushed a new package.  I also added another Optional to the DM4File class.  I don't see any unions with None left.  Let me know if that solves it.

**Comment by volks73** [comment]
Thank you! I updated my Python v3.9 application and I encountered no errors after upgrading to v1.0.2.

This issue has been resolved with release of v1.0.2 and it can be closed.
